title: parsec.ro
author:
  name: Claudiu Tănăselia
  email: claudiu@tanaselia.ro

show_excerpts: false

social_links:
    twitter: superparsec
    github:  ctanas
    facebook: claudiu.tanaselia
    google_scholar_id: njJE6nEAAAAJ
    mastodon:
    - username: superparsec
      instance: mastodon.social
url: https://parsec.ro
google_analytics: UA-19421559-1
markdown: kramdown
theme: minima
header_pages:
 - about.md
collections:
  r:
    output: true
  y:
    output: true
  v:
    output: true
