title: parsec.ro
author:
  name: Claudiu Tănăselia
  email: claudiu@tanaselia.ro

show_excerpts: false

source: https://github.com/ctanas/parsec-jupyter

social_links:
    twitter: superparsec
    github:  ctanas
    facebook: claudiu.tanaselia
    google_scholar_id: njJE6nEAAAAJ
    mastodon:
    - username: superparsec
      instance: mastodon.social

markdown: kramdown
theme: minima
header_pages:
 - about.md
